### ISSUE TITLE
add option to detect a language 

### ISSUE THREAD

**Issue by cheemzboi** [ahmeterenodaci/easygoogletranslate#1]
i wanna achieve something like this :

Input text: "ру́сский язы́к"
Output text: "Russian" 

Input text: "中文"
Output text: "Chinese" 

Input text: "にほんご"
Output text: "Japanese" 

Input text: "العَرَبِيَّة"
Output text: "Arabic"

using google api can we detect the lang ? if yes please add it to module

**Comment by ahmeterenodaci** [comment]
Unfortunately, this is not possible with this library.
