### ISSUE TITLE
apostrophe is not detected ??

### ISSUE THREAD

**Issue by ahmadkarimi4** [ahmeterenodaci/easygoogletranslate#2]
# Problem
- Apostrophe isnt being detected 

# Desired result 
Bankman-Fried, the former CEO of bankrupt cryptocurrency exchange FTX, lost his entire $16 billion fortune in one of the largest losses in history, reports Bloomberg. At the peak of the business, the entrepreneur's fortune was estimated at $ 26 billion.
If you allow me, I'll post a link.
Thanks

# Current result 
[![Img](https://i.ibb.co/P4tJMWn/image.png)](https://i.ibb.co/P4tJMWn/image.png)

# Code to Replicate issue 
```
from easygoogletranslate import EasyGoogleTranslate
koko="Бывший гендиректор обанкротившейся криптовалютной биржи FTX Бэнкман-Фрид потерял все свое состояние в $16 млрд. Это один из крупнейших в истории случаев утраты состояния, передает Блумберг. На пике бизнеса состояние предпринимателя оценивалось в $26 млрд."
koko1="""Если разрешите кину ссылку.
Спасибо"""
translator=EasyGoogleTranslate()
print(koko)
print(koko1)

def tr(text):
    result = translator.translate(f'{(text)}', target_language='en')
    return result

mk=tr(koko)
kk=tr(koko1)
print(mk)
print(kk)

```

**Comment by ahmeterenodaci** [comment]
Hey, I released a new update to fix this. 

If you have installed the package via pip, you can update it with the following command.

`pip install easygoogletranslate --upgrade`



Updated result:

![resim](https://user-images.githubusercontent.com/33299067/201543256-671c9e78-3beb-4851-964f-f5310c80f4c3.png)

**Comment by ahmadkarimi4** [comment]
thanks
